<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-VAL9S0L" ignored="0" name="SmokeTest" tests="6" failures="1" timestamp="2020-07-11T13:44:36 IST" time="89.966" errors="0">
  <testcase name="validateListeners" time="0.515" classname="com.DemoQATests.HomePageTest">
    <skipped/>
  </testcase> <!-- validateListeners -->
  <testcase name="validateListeners" time="0.001" classname="com.DemoQATests.HomePageTest">
    <skipped/>
  </testcase> <!-- validateListeners -->
  <testcase name="validateListeners" time="0.003" classname="com.DemoQATests.HomePageTest">
    <skipped/>
  </testcase> <!-- validateListeners -->
  <testcase name="validateListeners" time="0.003" classname="com.DemoQATests.HomePageTest">
    <failure type="java.lang.AssertionError" message="expected [3] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [2]
at com.DemoQATests.HomePageTest.validateListeners(HomePageTest.java:98)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- validateListeners -->
  <testcase name="validateDropDownOptions" time="3.77" classname="com.DemoQATests.HomePageTest"/>
  <testcase name="getCookies" time="0.101" classname="com.DemoQATests.HomePageTest"/>
</testsuite> <!-- SmokeTest -->
